#!/usr/bin/env python3
"""Download and normalize external Shadowrocket RULE-SET lists.

This script keeps generated lists in ./release/ so the main Shadowrocket
config can depend on BorbetOPC-owned raw GitHub URLs instead of third-party
raw URLs directly.
"""

from __future__ import annotations

import datetime as dt
import pathlib
import sys
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parents[1]
RELEASE = ROOT / "release"

SOURCES = {
    "ru-mobile-whitelist.list": "https://raw.githubusercontent.com/Master-Yoba/shadowrocket-rules/release/rules-geosite/geosite-ru-mobile-whitelist.list",
    "ru-category.list": "https://raw.githubusercontent.com/Master-Yoba/shadowrocket-rules/release/rules-geosite/geosite-category-ru.list",
    "geoip-ru.list": "https://raw.githubusercontent.com/Master-Yoba/shadowrocket-rules/release/rules-geoip/geoip-ru.list",
}

HEADER = """# Auto-generated by scripts/update_rules.py
# Source: {url}
# Updated: {updated_utc} UTC
# Do not edit manually; edit sources or whitelist.list instead.

"""


def download(url: str) -> str:
    req = urllib.request.Request(
        url,
        headers={"User-Agent": "BorbetOPC-Shadowrocket-Rules-Updater/1.0"},
    )
    with urllib.request.urlopen(req, timeout=60) as response:
        raw = response.read()
    return raw.decode("utf-8", errors="replace")


def normalize(text: str) -> str:
    lines: list[str] = []
    seen: set[str] = set()

    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if line in seen:
            continue
        seen.add(line)
        lines.append(line)

    lines.sort()
    return "\n".join(lines) + "\n"


def main() -> int:
    RELEASE.mkdir(parents=True, exist_ok=True)
    updated = dt.datetime.now(dt.UTC).strftime("%Y-%m-%d %H:%M:%S")

    for filename, url in SOURCES.items():
        print(f"Downloading {filename} from {url}")
        body = normalize(download(url))
        output = HEADER.format(url=url, updated_utc=updated) + body
        path = RELEASE / filename
        path.write_text(output, encoding="utf-8")
        print(f"Wrote {path.relative_to(ROOT)}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
